/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaliRouteImport } from './routes/wali'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as NikahRouteImport } from './routes/nikah'
import { Route as MahrRouteImport } from './routes/mahr'
import { Route as HalalRelationshipsRouteImport } from './routes/halal-relationships'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedSurveyRouteImport } from './routes/_authenticated/survey'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'

const WaliRoute = WaliRouteImport.update({
  id: '/wali',
  path: '/wali',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const NikahRoute = NikahRouteImport.update({
  id: '/nikah',
  path: '/nikah',
  getParentRoute: () => rootRouteImport,
} as any)
const MahrRoute = MahrRouteImport.update({
  id: '/mahr',
  path: '/mahr',
  getParentRoute: () => rootRouteImport,
} as any)
const HalalRelationshipsRoute = HalalRelationshipsRouteImport.update({
  id: '/halal-relationships',
  path: '/halal-relationships',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedSurveyRoute = AuthenticatedSurveyRouteImport.update({
  id: '/survey',
  path: '/survey',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/community': typeof CommunityRoute
  '/halal-relationships': typeof HalalRelationshipsRoute
  '/mahr': typeof MahrRoute
  '/nikah': typeof NikahRoute
  '/verify-email': typeof VerifyEmailRoute
  '/wali': typeof WaliRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/survey': typeof AuthenticatedSurveyRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/community': typeof CommunityRoute
  '/halal-relationships': typeof HalalRelationshipsRoute
  '/mahr': typeof MahrRoute
  '/nikah': typeof NikahRoute
  '/verify-email': typeof VerifyEmailRoute
  '/wali': typeof WaliRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/survey': typeof AuthenticatedSurveyRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/community': typeof CommunityRoute
  '/halal-relationships': typeof HalalRelationshipsRoute
  '/mahr': typeof MahrRoute
  '/nikah': typeof NikahRoute
  '/verify-email': typeof VerifyEmailRoute
  '/wali': typeof WaliRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/survey': typeof AuthenticatedSurveyRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/community'
    | '/halal-relationships'
    | '/mahr'
    | '/nikah'
    | '/verify-email'
    | '/wali'
    | '/dashboard'
    | '/settings'
    | '/survey'
    | '/auth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/community'
    | '/halal-relationships'
    | '/mahr'
    | '/nikah'
    | '/verify-email'
    | '/wali'
    | '/dashboard'
    | '/settings'
    | '/survey'
    | '/auth/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/community'
    | '/halal-relationships'
    | '/mahr'
    | '/nikah'
    | '/verify-email'
    | '/wali'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings'
    | '/_authenticated/survey'
    | '/auth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  CommunityRoute: typeof CommunityRoute
  HalalRelationshipsRoute: typeof HalalRelationshipsRoute
  MahrRoute: typeof MahrRoute
  NikahRoute: typeof NikahRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  WaliRoute: typeof WaliRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wali': {
      id: '/wali'
      path: '/wali'
      fullPath: '/wali'
      preLoaderRoute: typeof WaliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nikah': {
      id: '/nikah'
      path: '/nikah'
      fullPath: '/nikah'
      preLoaderRoute: typeof NikahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mahr': {
      id: '/mahr'
      path: '/mahr'
      fullPath: '/mahr'
      preLoaderRoute: typeof MahrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/halal-relationships': {
      id: '/halal-relationships'
      path: '/halal-relationships'
      fullPath: '/halal-relationships'
      preLoaderRoute: typeof HalalRelationshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/survey': {
      id: '/_authenticated/survey'
      path: '/survey'
      fullPath: '/survey'
      preLoaderRoute: typeof AuthenticatedSurveyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSurveyRoute: typeof AuthenticatedSurveyRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSurveyRoute: AuthenticatedSurveyRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  CommunityRoute: CommunityRoute,
  HalalRelationshipsRoute: HalalRelationshipsRoute,
  MahrRoute: MahrRoute,
  NikahRoute: NikahRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  WaliRoute: WaliRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
