// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { getServerSupabasePublicConfigs } from "./public-config";
import { supabaseConfigForToken } from "@/lib/supabase-token";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

export const requireSupabaseAuth = createMiddleware({ type: "function" }).server(
  async ({ next }) => {
    const request = getRequest();

    if (!request?.headers) {
      throw new Error("Unauthorized: No request headers available");
    }

    const authHeader = request.headers.get("authorization");

    if (!authHeader) {
      throw new Error("Unauthorized: No authorization header provided");
    }

    if (!authHeader.startsWith("Bearer ")) {
      throw new Error("Unauthorized: Only Bearer tokens are supported");
    }

    const token = authHeader.replace("Bearer ", "");
    if (!token) {
      throw new Error("Unauthorized: No token provided");
    }

    // Use the untrusted issuer only to choose the destination. Never send a
    // member token to every configured Supabase project while looking for a match.
    const config = supabaseConfigForToken(token, getServerSupabasePublicConfigs());
    if (!config) {
      throw new Error("Unauthorized: Your session has expired. Please sign in again.");
    }

    const supabase = createClient<Database>(config.url, config.publishableKey, {
      global: {
        fetch: createSupabaseFetch(config.publishableKey),
        headers: { Authorization: `Bearer ${token}` },
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    });

    let claims: { sub: string; [key: string]: unknown } | undefined;
    try {
      const result = await supabase.auth.getClaims(token);
      if (!result.error && result.data?.claims?.sub) claims = result.data.claims;
    } catch {
      claims = undefined;
    }
    if (!claims) throw new Error("Unauthorized: Your session has expired. Please sign in again.");

    return next({
      context: {
        supabase,
        userId: claims.sub,
        claims,
      },
    });
  },
);
